(defun blind-check (url class)
  (let* ((corp (downloaded-link-corpus url))
         (sibling-classes (subclasses (parent-class class))))
    (multiple-value-bind (scores probsum) (scores (list-keys corp)
                                                  sibling-classes
                                                  (map-to-hash #'(lambda (option)
                                                                   (if (equal option class)
                                                                       (add-corpuses (get-recursive-corpus option)
                                                                                     (scale-corpus corp -1))
                                                                       (get-recursive-corpus option)))
                                                               sibling-classes)
                                                  (map-to-hash #'(lambda (option)
                                                                   (if (equal option class)
                                                                       (- (get-word-count option)
                                                                          (length (list-keys (downloaded-link-corpus url))))
                                                                       (get-word-count option)))
                                                               sibling-classes)
                                                  nil)
      (if (and (subclasses class)
               (< probsum (ln 1/10)))
          (print (concat "Cannot sensibly class link: " url " within class: " (parent-class class) ". Probsum: " (exp probsum))))
      (gethash class (map-to-hash #'cdr
                                  (list-hashes scores)
                                  :key-fun #'car)))))

(defun integrity (class)
  (let ((links (recursive-links class)))
    (/ (apply #'+ (mapcar #'(lambda (link)
                              (blind-check link class))
                          links))
       (length links))))

(defun integrity-benchmark (class)
  (dolist (i (subclasses class))
    (integrity-benchmark i))
  (print (concat "Integrity of " class ": " (integrity class))))
