(defun main ()
  ;(print "Creating imported classes...")
  ;(create-all-import-classes)
  (print "Downloading missing files...")
  (redownload "/")
  (print "Building core text database...")
  (terpri)
  (build-core-text-database)
  (print "Reading data...")
  (refresh-imports)
  (read-saved)
  (read-comments)
  (read-weights)
  (build-subclasses)
  (print (subclasses "/"))
  (print "Building corpora...")
  (rebuild-corpus)
  (print "All done. Opening classifier.")
  (run))
