(defun main ()
  (print "Creating imported classes...")
  (create-all-import-classes)
  (print "Downloading missing files...")
  (redownload "/")
  (print "Building core text database...")
  (terpri)
  (build-core-text-database)
  (print "Building corpora...")
  (rebuild-corpus)
  (print "All done. Opening classifier.")
  (run))
