(defun main ()
  (print "Reading data...")
  (read-config)
  (read-saved)
  (build-subclasses)
  (print "Downloading missing files...")
  (redownload)
  (print "Building core text database...")
  (build-core-text-database)
  (print "Reading imports...")
  (refresh-imports)
  (build-subclasses)
  (print "Building corpora...")
  (rebuild-corpus)
  (refresh-comprehensible-corp)
  (print "All done. Opening classifier.")
  (run))

(defun view-crawler-results ()
  (ignore-imports)
  (print "Reading config data...")
  (read-config)
  (print "Reading crawler results...")
  (read-discovered)
  (build-subclasses)
  (rebuild-url-counts)
  (print "All done. Opening results.")
  (display-crawl-results))
