(defun main ()
  (print "Downloading missing files...")
  (redownload)
  (print "Building core text database...")
  (terpri)
  (build-core-text-database)
  (print "Reading data...")
  (refresh-imports)
  (read-saved)
  (read-config)
  (build-subclasses)
  (print "Building corpora...")
  (rebuild-corpus)
  (refresh-comprehensible-corp)
  (print "All done. Opening classifier.")
  (run))
